server:
  port: 9095
  session:
    timeout: 60
spring:
  application:
      name: pl-prd
  datasource:
    url:  jdbc:mysql://47.52.221.88:3306/product?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:  ibracket
    password:  123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
swagger:
  show: true
imgpush:
  url: http://hc.sncsrv.com/index.php/interface/JPushImg

del:
  time: 1440
  url: /Users/YZBbanban/Desktop/test/ssss


